eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: service-feign
#自定义负载均衡配置 clientname+ribbon+NFLoadBalancerRuleClassName+自定义负载均衡class路径
service-hi:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#开启熔断
feign:
  hystrix:
    enabled: true