spring:
  application:
    name: service-feign
#zipkin服务器路径
  zipkin:
    base-url: http://localhost:9411
#自定义负载均衡配置 clientname+ribbon+NFLoadBalancerRuleClassName+自定义负载均衡class路径
service-hi:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#开启熔断
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #hystrix超时时间设置

