eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

server:
  port: 8762

spring:
  application:
    name: service-hi
  #zipkin:
    #base-url: http://localhost:9411 #zipkin链路

security:
  user:
    name: admin
    password: admin123
  basic:
    enabled: true
