eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8764
spring:
  application:
    name: service-ribbon
  #zipkin:
    #base-url: localhost:9411 #zipkin链接
security:
  basic:
    enabled: false

